[[Hyperparameters]]

game_tick_count_values = [500]
game_seed_values = [2]
probability_resolution_values = [6]
initial_tile_gold_values = [1000, 0]
initial_tile_wood_values = [2000]


[[Settings]]

plotting_frame_subselectecion_factor = 10